server.port=8082

# Active profile (use 'dev' for local, 'prod' for production)
spring.profiles.active=prod

# Common JPA settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

